# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-algolia

# Site settings
url: 'https://chrisowen491.github.io'
baseurl: '/architecture-docs'
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: decisions/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Decisions
  url: /decisions/
- title: Categories
  url: /categories/  
- title: Search
  url: /search/  

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Architecture Decisions
    output: true
    description: "ADR Entries"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts    
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

algolia:
  application_id: AF54HS5SSH
  index_name: reference
  search_only_api_key: 29ee457e00ff639dc82aae13c37c843d